"use client"
import { useState } from "react"
import { Button } from "@/components/ui/button"

interface TextDetectorProps {
  onTextAnalyze: (text: string) => void
  isAnalyzing: boolean
}

export default function TextDetector({ onTextAnalyze, isAnalyzing }: TextDetectorProps) {
  const [text, setText] = useState("")
  const [isFocused, setIsFocused] = useState(false)

  const handleAnalyze = () => {
    if (text.trim()) {
      onTextAnalyze(text)
    }
  }

  const handleClear = () => {
    setText("")
  }

  return (
    <div className="max-w-2xl mx-auto">
      <div className="glass-card p-8">
        <div className="mb-6">
          <div className="inline-block p-3 rounded-lg bg-secondary/10 border border-secondary/30 mb-4">
            <svg className="w-6 h-6 text-secondary" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z"
              />
            </svg>
          </div>
          <h3 className="text-2xl font-bold text-foreground mb-2">Text AI Detector</h3>
          <p className="text-muted-foreground">Paste your text to check if it was generated by AI</p>
        </div>

        <div className="space-y-4">
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            onFocus={() => setIsFocused(true)}
            onBlur={() => setIsFocused(false)}
            placeholder="Paste your text here... (minimum 50 characters for best results)"
            className={`w-full h-40 p-4 rounded-lg bg-input border transition-all duration-300 resize-none focus:outline-none ${
              isFocused ? "border-secondary/60 glow-blue bg-card/60" : "border-border/30 hover:border-secondary/40"
            } text-foreground placeholder-muted-foreground`}
          />

          <div className="flex gap-3 justify-between items-center">
            <span className="text-sm text-muted-foreground">{text.length} characters</span>
            <div className="flex gap-3">
              <Button
                onClick={handleClear}
                variant="outline"
                disabled={!text || isAnalyzing}
                className="bg-transparent"
              >
                Clear
              </Button>
              <Button
                onClick={handleAnalyze}
                disabled={text.length < 50 || isAnalyzing}
                className="bg-secondary text-secondary-foreground hover:bg-secondary/90 glow-blue"
              >
                {isAnalyzing ? "Analyzing..." : "Analyze Text"}
              </Button>
            </div>
          </div>

          {text.length < 50 && text.length > 0 && (
            <p className="text-xs text-secondary/70 text-center">Add at least {50 - text.length} more characters</p>
          )}
        </div>
      </div>
    </div>
  )
}
